#***Week 2: Data Collection, Cleaning, and Preprocessing for Logistics Analysis***

##*Project*

Logistics Delivery Performance Analysis and Strategic Planning Using Python

##*Objective*

This notebook focuses on collecting, inspecting, cleaning, and preprocessing logistics data using Python. The objective is to identify and resolve common data quality issues such as missing values, duplicate records, inconsistent data types, invalid values, and outliers. Feature engineering and normalization techniques are also applied to prepare the dataset for reliable logistics analysis and future predictive modeling.
The preprocessing workflow uses the Brazilian E-Commerce Public Dataset by Olist, with particular focus on order and delivery information.

##**Notebook Contents**

1. Objective

2. Dataset Collection and Description

3. Python Environment Setup

4. Dataset Loading

5. Initial Data Inspection

6. Data Quality Assessment

7. Data Type Conversion

8. Missing Value Analysis

9. Duplicate Record Detection

10. Data Consistency Validation

11. Feature Engineering

12. Outlier Detection

13. Outlier Treatment Strategy

14. Data Normalization

15. Final Data Validation

16. Preprocessing Pipeline Summary

17. Reflection

18. Conclusion

##**2. Dataset Collection and Description**

###*Dataset Source*

The dataset used in this project is the Brazilian E-Commerce Public Dataset by Olist, a publicly available e-commerce dataset containing information about orders, customers, products, payments, freight, reviews, and delivery performance.
For this preprocessing task, the Orders dataset is used because it contains important logistics-related information such as order status, purchase timestamp, approval timestamp, actual delivery timestamp, and estimated delivery date.

###*Dataset Characteristics*

The Orders dataset contains approximately 89,000 order records and seven columns. These records represent e-commerce orders and their processing and delivery information.
Important fields include:

order_id – unique identifier for each order.

customer_id – identifier of the customer associated with the order.

order_status – current status of the order.

order_purchase_timestamp – date and time when the order was placed.

order_approved_at – date and time when the order was approved.

order_delivered_timestamp – actual delivery date and time.

order_estimated_delivery_date – estimated delivery date.

###*Relevance to Logistics*

The dataset is suitable for logistics analysis because it contains both actual and estimated delivery information. This makes it possible to calculate delivery duration, identify unusual delivery records, evaluate delivery performance, and prepare the data for future predictive analysis.

In [1]:
import pandas as pd

print("pandas version :", pd.__version__)
print("pandas environment is ready......")

pandas version : 2.2.3
pandas environment is ready......

In [2]:
orders = pd.read_csv("/content/df_Orders.csv")

print("Dataset loaded successfully!")
print("Rows:", orders.shape[0])
print("Columns:", orders.shape[1])

orders.head()

Dataset loaded successfully!
Rows: 89316
Columns: 7

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18

In [3]:
print("Missing values in each column:")
print(orders.isnull().sum())

print("\nMissing percentage in each column:")
missing_percentage = (orders.isnull().sum() / len(orders)) * 100
print(missing_percentage.round(2))

print("\nDuplicate rows:")
print(orders.duplicated().sum())

print("\nOrder status distribution:")
print(orders["order_status"].value_counts())

print("\nStatistical summary:")
display(orders.describe(include="all"))

Missing values in each column:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   9
order_delivered_timestamp        1889
order_estimated_delivery_date       0
dtype: int64

Missing percentage in each column:
order_id                         0.00
customer_id                      0.00
order_status                     0.00
order_purchase_timestamp         0.00
order_approved_at                0.01
order_delivered_timestamp        2.11
order_estimated_delivery_date    0.00
dtype: float64

Duplicate rows:
0

Order status distribution:
order_status
delivered      87428
shipped          936
canceled         409
processing       273
invoiced         266
unavailable        2
approved           2
Name: count, dtype: int64

Statistical summary:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
count,89316,89316,89316,89316,89307,87427,89316
unique,89316,89316,7,72775,68215,71143,444
top,Xo1fqyXOC6CR,rhevVNXYJnEs,delivered,2017-08-08 20:26:31,2017-08-08 20:43:31,2017-08-14 12:46:18,2017-12-20
freq,1,1,87428,87,87,87,500

##**5. Initial Data Inspection**

The first stage of preprocessing is to understand the structure and characteristics of the raw dataset. The dataset shape, column names, data types, sample records, and summary information are examined before performing any cleaning operations.
This step helps identify potential problems that may affect subsequent analysis.

In [4]:
print("Dataset Shape:", orders.shape)

print("\nColumn Names:")
print(orders.columns.tolist())

print("\nFirst 5 Records:")
display(orders.head())

print("\nDataset Information:")
orders.info()

Dataset Shape: (89316, 7)

Column Names:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_timestamp', 'order_estimated_delivery_date']

First 5 Records:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  object
 1   customer_id                    89316 non-null  object
 2   order_status                   89316 non-null  object
 3   order_purchase_timestamp       89316 non-null  object
 4   order_approved_at              89307 non-null  object
 5   order_delivered_timestamp      87427 non-null  object
 6   order_estimated_delivery_date  89316 non-null  object
dtypes: object(7)
memory usage: 4.8+ MB

##**6. Data Quality Assessment**

Data quality is assessed by checking missing values, duplicate records, categorical distributions, and basic statistical information. These checks help identify problems that need to be addressed before performing further analysis.
The following checks are performed:

Missing-value detection

Missing-value percentage calculation

Duplicate-record detection

Order-status distribution

Numerical summary statistics

In [5]:
print("Missing values in each column:")
print(orders.isnull().sum())

print("\nMissing percentage in each column:")
missing_percentage = (orders.isnull().sum() / len(orders)) * 100
print(missing_percentage.round(2))

print("\nDuplicate rows:")
print(orders.duplicated().sum())

print("\nOrder status distribution:")
print(orders["order_status"].value_counts())

print("\nStatistical summary:")
display(orders.describe(include="all"))

Missing values in each column:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   9
order_delivered_timestamp        1889
order_estimated_delivery_date       0
dtype: int64

Missing percentage in each column:
order_id                         0.00
customer_id                      0.00
order_status                     0.00
order_purchase_timestamp         0.00
order_approved_at                0.01
order_delivered_timestamp        2.11
order_estimated_delivery_date    0.00
dtype: float64

Duplicate rows:
0

Order status distribution:
order_status
delivered      87428
shipped          936
canceled         409
processing       273
invoiced         266
unavailable        2
approved           2
Name: count, dtype: int64

Statistical summary:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
count,89316,89316,89316,89316,89307,87427,89316
unique,89316,89316,7,72775,68215,71143,444
top,Xo1fqyXOC6CR,rhevVNXYJnEs,delivered,2017-08-08 20:26:31,2017-08-08 20:43:31,2017-08-14 12:46:18,2017-12-20
freq,1,1,87428,87,87,87,500

##**7. Data Type Conversion**

The timestamp columns are initially stored as text values. For logistics analysis, these columns must be converted into datetime format so that date differences and delivery durations can be calculated correctly.
The errors="coerce" option converts invalid date values into missing values instead of causing the program to stop. This allows invalid or incorrectly formatted dates to be identified during the data-quality assessment.

In [6]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_timestamp",
    "order_estimated_delivery_date"
]

for column in date_columns:
    orders[column] = pd.to_datetime(
        orders[column],
        errors="coerce"
    )

print("Data types after conversion:")
orders[date_columns].dtypes
orders.info()

Data types after conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  object
 1   customer_id                    89316 non-null  object
 2   order_status                   89316 non-null  object
 3   order_purchase_timestamp       89316 non-null  datetime64[ns]
 4   order_approved_at              89307 non-null  datetime64[ns]
 5   order_delivered_timestamp      87427 non-null  datetime64[ns]
 6   order_estimated_delivery_date  89316 non-null  datetime64[ns]
dtypes: datetime64[ns](4), object(3)
memory usage: 4.8+ MB

##**8. Missing Value Analysis**

Missing values are common in real-world logistics datasets. They must be analyzed carefully because replacing or removing missing values without understanding their meaning can introduce bias.
In this dataset, missing values may occur in approval or delivery timestamps. A missing delivery timestamp can be meaningful because an order may not have reached the delivered stage.
Therefore, missing values are first identified and analyzed rather than automatically replaced.

###*Treatment Strategy*

Missing approval timestamps will be retained because only a small number of records are affected.

Missing delivery timestamps will be retained when they correspond to orders that have not been delivered.

Missing values will not be replaced with arbitrary values because doing so could create false delivery information.

In [7]:
print("Missing values after date conversion:")
print(orders.isnull().sum())

Missing values after date conversion:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   9
order_delivered_timestamp        1889
order_estimated_delivery_date       0
dtype: int64

In [8]:
print("Missing delivery timestamps by order status:")
print(
    orders[orders["order_delivered_timestamp"].isnull()]
    ["order_status"]
    .value_counts()
)

Missing delivery timestamps by order status:
order_status
shipped        936
canceled       404
processing     273
invoiced       266
delivered        6
unavailable      2
approved         2
Name: count, dtype: int64

##**9. Duplicate Record Detection**

Duplicate records can lead to double-counting and incorrect logistics performance measurements. Therefore, duplicate rows are checked before further analysis.
If duplicate records are found, they can be removed using pandas drop_duplicates() method. In this dataset, the duplicate count is examined before deciding whether removal is necessary.

In [9]:
duplicate_count = orders.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

##**10. Data Consistency Validation**

Data consistency checks are performed to identify values that may be logically incorrect for logistics analysis.
The following conditions are examined:

Negative delivery durations

Extremely long delivery durations

Delivered orders without delivery timestamps

Unexpected relationships between order status and delivery information

These checks help distinguish genuine operational variations from potentially invalid records.

In [10]:
delivered_without_timestamp = (
    (orders["order_status"] == "delivered") &
    (orders["order_delivered_timestamp"].isnull())
).sum()

print(
    "Delivered orders without delivery timestamp:",
    delivered_without_timestamp
)

Delivered orders without delivery timestamp: 6

In [11]:
orders["delivery_days"] = (
    orders["order_delivered_timestamp"]
    - orders["order_purchase_timestamp"]
).dt.days

print("Negative delivery durations:")
print((orders["delivery_days"] < 0).sum())

print("\nDelivery durations greater than 100 days:")
print((orders["delivery_days"] > 100).sum())

Negative delivery durations:
0

Delivery durations greater than 100 days:
43

##**11. Feature Engineering**

A new feature named delivery_days is created to represent the number of days between the order purchase date and the actual delivery date.
This feature is useful for logistics analysis because it converts timestamp information into a numerical measure that can be analyzed statistically.
The calculation is performed only when both purchase and delivery timestamps are available.

In [12]:
orders[[
    "order_purchase_timestamp",
    "order_delivered_timestamp",
    "delivery_days"
]].head(10)

  order_purchase_timestamp order_delivered_timestamp  delivery_days
0      2017-10-22 18:57:54       2017-10-26 22:19:52            4.0
1      2018-06-20 21:40:31       2018-07-03 22:51:22           13.0
2      2018-02-16 16:19:31       2018-02-27 01:29:50           10.0
3      2018-08-18 18:04:29       2018-08-27 20:03:51            9.0
4      2017-12-22 16:44:04       2018-01-05 19:22:49           14.0
5      2017-09-01 14:38:16       2017-09-15 18:57:50           14.0
6      2018-04-23 21:03:00       2018-04-25 20:14:38            1.0
7      2018-02-23 14:49:39       2018-04-02 14:12:50           37.0
8      2017-11-24 19:12:37       2017-12-11 13:09:32           16.0
9      2017-11-30 11:48:21       2017-12-14 16:38:47           14.0

In [13]:
print("Delivery time statistics:")
display(orders["delivery_days"].describe())

Delivery time statistics:

count    87427.000000
mean        11.969129
std          9.277678
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: delivery_days, dtype: float64

##**12. Outlier Detection**

Outliers are observations that are unusually different from the majority of the data. In logistics, extremely long delivery times may indicate operational delays, unusual circumstances, or data-quality problems.
The Interquartile Range (IQR) method is used to identify potential outliers.
The IQR is calculated as:
IQR = Q3 − Q1
The lower and upper boundaries are calculated as:
Lower Bound = Q1 − 1.5 × IQR
Upper Bound = Q3 + 1.5 × IQR
Records outside these boundaries are considered potential outliers.

In [14]:
Q1 = orders["delivery_days"].quantile(0.25)
Q3 = orders["delivery_days"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Q1: 6.0
Q3: 15.0
IQR: 9.0
Lower Bound: -7.5
Upper Bound: 28.5

In [15]:
outliers = orders[
    (orders["delivery_days"] < lower_bound) |
    (orders["delivery_days"] > upper_bound)
]

print("Number of potential outliers:", len(outliers))

Number of potential outliers: 4343

##**13. Outlier Treatment Strategy**

Potential outliers are not automatically removed because extreme delivery times can represent genuine logistics problems.
For example, an unusually long delivery duration may indicate a delayed shipment, transportation issue, operational bottleneck, or exceptional order.
Therefore, the identified outliers are retained for the current logistics analysis unless a record is proven to be invalid. Instead of deleting potentially valuable information, the outlier records can be flagged for further investigation.
This approach prevents genuine operational problems from being hidden during analysis.

In [16]:
orders["delivery_outlier"] = (
    (orders["delivery_days"] < lower_bound) |
    (orders["delivery_days"] > upper_bound)
)

print("Outlier flag distribution:")
print(orders["delivery_outlier"].value_counts())

Outlier flag distribution:
delivery_outlier
False    84973
True      4343
Name: count, dtype: int64

##**14. Data Normalization**

Normalization is used to transform numerical values to a common scale. Min-Max normalization converts values into a range between 0 and 1.
The formula is:
Normalized Value = (X − Minimum) / (Maximum − Minimum)
Normalization can be useful when numerical variables with different scales are later used in machine-learning algorithms or other analytical techniques.
The normalized delivery duration is stored in a separate column so that the original delivery-time information is preserved.

In [17]:
delivery_min = orders["delivery_days"].min()
delivery_max = orders["delivery_days"].max()

orders["delivery_days_normalized"] = (
    (orders["delivery_days"] - delivery_min) /
    (delivery_max - delivery_min)
)

orders[
    ["delivery_days", "delivery_days_normalized"]
].head(10)

   delivery_days  delivery_days_normalized
0            4.0                  0.019139
1           13.0                  0.062201
2           10.0                  0.047847
3            9.0                  0.043062
4           14.0                  0.066986
5           14.0                  0.066986
6            1.0                  0.004785
7           37.0                  0.177033
8           16.0                  0.076555
9           14.0                  0.066986

In [18]:
print(
    "Minimum normalized value:",
    orders["delivery_days_normalized"].min()
)

print(
    "Maximum normalized value:",
    orders["delivery_days_normalized"].max()
)

Minimum normalized value: 0.0
Maximum normalized value: 1.0

##**15. Final Data Validation**

After preprocessing, the dataset is checked again to confirm that the transformations were applied correctly.
The final validation includes:

Dataset dimensions

Data types

Missing values

Duplicate records

Delivery-time statistics

Outlier flags

Normalized values

This ensures that the resulting dataset is suitable for further logistics analysis and future predictive modeling.

In [19]:
print("Final dataset shape:", orders.shape)

print("\nFinal data types:")
orders.info()

print("\nRemaining missing values:")
print(orders.isnull().sum())

print("\nDuplicate rows:")
print(orders.duplicated().sum())

Final dataset shape: (89316, 10)

Final data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  object
 1   customer_id                    89316 non-null  object
 2   order_status                   89316 non-null  object
 3   order_purchase_timestamp       89316 non-null  datetime64[ns]
 4   order_approved_at              89307 non-null  datetime64[ns]
 5   order_delivered_timestamp      87427 non-null  datetime64[ns]
 6   order_estimated_delivery_date  89316 non-null  datetime64[ns]
 7   delivery_days                  87427 non-null  float64
 8   delivery_outlier               89316 non-null  bool
 9   delivery_days_normalized       87427 non-null  float64
dtypes: bool(1), datetime64[ns](4), float64(2), object(3)
memory usage: 6.2+ MB

Remaining missing values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   9
order_delivered_timestamp        1889
order_estimated_delivery_date       0
delivery_days                    1889
delivery_outlier                    0
delivery_days_normalized         1889
dtype: int64

Duplicate rows:
0

In [20]:
print("Final delivery-time statistics:")
display(orders["delivery_days"].describe())

Final delivery-time statistics:

count    87427.000000
mean        11.969129
std          9.277678
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: delivery_days, dtype: float64

In [21]:
print("Outlier counts:")
print(orders["delivery_outlier"].value_counts())

print("\nNormalized delivery-time range:")
print(
    orders["delivery_days_normalized"].min(),
    "to",
    orders["delivery_days_normalized"].max()
)

Outlier counts:
delivery_outlier
False    84973
True      4343
Name: count, dtype: int64

Normalized delivery-time range:
0.0 to 1.0

## **16. Preprocessing Pipeline Summary**

**Raw Olist Dataset**  
↓  
**Dataset Inspection**  
↓  
**Data Quality Assessment**  
↓  
**Data Type Conversion**  
↓  
**Missing Value Analysis**  
↓  
**Duplicate Detection**  
↓  
**Data Consistency Validation**  
↓  
**Feature Engineering**  
↓  
**Outlier Detection & Flagging**  
↓  
**Min-Max Normalization**  
↓  
**Final Validation**  
↓  
**Analysis-Ready Dataset**

### **Summary**

The preprocessing workflow improves the reliability and usability of the logistics dataset while preserving meaningful operational information, such as unusually long delivery durations. The prepared dataset can be used as a foundation for further logistics analysis and future predictive modeling.

##**17. Reflection**

This preprocessing task demonstrated that data quality is an important foundation for logistics analytics. Raw logistics data can contain missing values, inconsistent data types, duplicate records, and unusual observations that may affect analytical results.
One important learning from this task was that missing values should not always be replaced automatically. In logistics data, a missing delivery timestamp may have a business meaning, such as an order that has not yet been delivered. Similarly, outliers should not automatically be deleted because unusually long delivery times may represent genuine operational delays.
The preprocessing process also demonstrated the importance of feature engineering. Converting timestamp information into delivery duration created a useful numerical feature for logistics analysis. Normalization further prepared numerical data for potential future machine-learning applications.
Overall, high-quality preprocessing helps produce more reliable KPIs, analytical results, and predictive models. It also supports better logistics decision-making by ensuring that important operational patterns are not hidden or distorted by poor-quality data.

##**18. Conclusion**

This Week 2 task developed a structured data collection, cleaning, and preprocessing workflow for logistics analysis using the Brazilian E-Commerce Public Dataset by Olist.
The dataset was systematically inspected to identify missing values, duplicate records, data-type issues, and potential inconsistencies. Timestamp fields were converted into appropriate datetime formats, and a delivery-duration feature was created to support logistics analysis.
Missing values were analyzed according to their business meaning rather than being replaced blindly. Duplicate records were checked, and potential outliers in delivery duration were identified using the IQR method. Instead of automatically deleting extreme delivery observations, they were flagged for further investigation because they may represent genuine logistics delays.
Min-Max normalization was also applied to the delivery-duration feature to demonstrate preparation for future analytical and machine-learning applications.
The resulting preprocessing workflow provides a more reliable foundation for future logistics analysis, predictive modeling, customer or order segmentation, and logistics optimization. This task demonstrates how systematic data preparation can improve the quality of analytical insights and support data-driven logistics decision-making.

In [22]:
orders.to_csv(
    "/content/Week_2_Preprocessed_Orders.csv",
    index=False
)

print("Preprocessed dataset saved successfully!")

Preprocessed dataset saved successfully!